### PR TITLE
Features

### PR DESCRIPTION
**Pull request by teekaytech**
We cloned a responsive copy of The Next Web homepage. Kindly review and comment as required.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @teekaytech and @NiiazalyDzhumaliev 
### Good job done so far :clap: However, you have a few issues to solve before your project could be approved.
- Fix your navigation to resemble the original website
### Yours
navigation
### Original
original
- Fix your footer to resemble the original design
footer
- On mobile devices, fix the images from being squeezed
mobile images
### Make these changes and resubmit for another code review. Good luck.
- Contact me on slack @iamraymond for any clarification.
- Happy coding!

**Comment by NiiazalyDzhumaliev** [comment]
We have solved the requested issues. Please recheck the project.

**Comment by mikenath223** [comment]
Pull Request currently under review by Michgolden Ukeje (TSE)
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Great Job Team 👏👌

You've done quite well on this, @teekaytech and @NiiazalyDzhumaliev .  👏👏

However, there remain a few changes you need to make before moving forward.

- [x] Add a logo to the top navbar as seen on the original webpage 👇 [Screenshot]
tnw-review
- [x] Also make the top navbar sticky, refer to the image above.

Kindly make these changes and submit for another code review
Feel free to contact me on slack.
Best of luck. 👍👍

**Comment by NiiazalyDzhumaliev** [comment]
Thank you for comments. We added the navbar logo and made it sticky. Please review the changes again.

**Comment by uryelah** [comment]
Hello **Taofeek Olalere** & **Niiazaly Dzhumaliev**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Great job with the fixes from the last reviews.🎇**

You did a great job with positioning and responsiveness.

There are still some issues to work through so hang in there 💪 

---------    

### Required changes 🛠 
---------

- [x] Please use the same logo as the one in the [original page.](https://thenextweb.com/). Yours has a background that's not matching the original design.

It should also take the full height of the white navbar.

Screenshot_2020-03-23 TNW(2)
**Original logo**
Screenshot_2020-03-23 TNW - International technology news, business and culture(2)
- [x] Pay attention to the collapsed menu icon color too:

-----

- [x] When the logo disappears from the first article on medium screens the gradient under it also disappears.

Screenshot_2020-03-23 TNW(3)
**Original main article on medium screens**
Screenshot_2020-03-23 TNW - International technology news, business and culture(3)

----

-  [ ] The 'Latest funding' and 'Apps' sections use tons of orange. You are using pink.
You don't need to try to guess the color you should use, try using an[ eyedropper or color picker](https://developer.mozilla.org/en-US/docs/Tools/Eyedropper) extension to get the exact color you need.

Notice the color difference comparing the screencaps bellow:

Screenshot_2020-03-23 TNW(4)
Screenshot_2020-03-23 TNW - International technology news, business and culture(4)
-----
Screenshot_2020-03-23 TNW(5)
Screenshot_2020-03-23 TNW - International technology news, business and culture(5)

--------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by NiiazalyDzhumaliev** [comment]
Fixed even very small details, please review again.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### You've done quite well team 👏👏👏
To have worked on the requested changes in a short time is wonderful @teekaytech  and @NiiazalyDzhumaliev 👍👍

However you haven't made all the changes, the previous reviewer mentioned:

Remember this project is about replicating the [The Next Web](https://thenextweb.com/) website _**putting emphasis on how it behaves differently depending on the size of the screen where the website is rendered**_.
Kindly keep scrolling down to the last item and ensure you read carefully, thanks 👇👇

Changes Required | Screenshot
-------------------- | --------------
Remove image gradient from the first article when it is rendered on medium screen | This is yours This is yours  **Yet it's supposed to look this way** 👇tnw-review
-------------- | -------------
Also, change image icon color on smaller resolution screen | This is yours 👇yours1img **Yet it's supposed to look this way** 👇 yours2img
-------------- | -------------

- [ ] Required - Kindly delete comments on your CSS files.

Make the requested above changes and submit another pull request.
Best of luck once more. 👍👍

**Comment by NiiazalyDzhumaliev** [comment]
Change the logo image to the gradient, delete gradient when less than 1024px, delete all comments in CSS files.

**Comment by NiiazalyDzhumaliev** [comment]
Change the live demo also

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Good job you have done for also making changes from previous reviews :clap: I, therefore, approve of this project. Congratulations :boom: :100:
### You can merge and submit a project completion form from your dashboard. Good luck with the next project. 
- Happy coding!

**Pull request merged**
